# Generated by Django 4.1.7 on 2023-05-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_libro',
            name='estado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
