# Generated by Django 4.1.7 on 2023-05-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_pedido_libro_estado_pedido_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido_libro',
            old_name='cantidad_libros',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='pedido_libro',
            old_name='precio_total_libros',
            new_name='precio_total',
        ),
    ]
