# Generated by Django 4.1.7 on 2023-05-15 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_libro_cantidad_delete_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_total', models.FloatField(default=0)),
                ('vendido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
